# Search
search:
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: 淮城一只猫
    url: https://iiong.com/

# navigation menu
menu:
  - name: Home
    slug: 首页
    url: /
  - name: archives
    slug: 归档
    url: /archives
  - name: about
    slug: 关于
    url: /about

# widgets
widgets:
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
