# Search
search:
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: 淮城一只猫
    url: https://iiong.com/

# navigation menu
menu:
  - name: 首页
    slug: Home
    url: /
  - name: 归档
    slug: archives
    url: /archives
  - name: 关于
    slug: about
    url: /about

# widgets
widgets:
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
